- name: Initialize the Kubernetes cluster using kubeadm
  command: "kubeadm init --apiserver-advertise-address={{ hostvars['k8s-master'].ansible_ssh_host }} --apiserver-cert-extra-sans={{ hostvars['k8s-master'].ansible_ssh_host }} --pod-network-cidr=192.168.0.0/16"
