- name: Add an apt signing key for Docker
  apt_key:
    url: https://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://mirrors.aliyun.com/docker-ce/linux/ubuntu xenial stable
    state: present

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce=18.06.2~ce~3-0~ubuntu

- name: Copy docker daemon.json
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json

- name: Restart docker daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    group: docker