- name: create .kube directory
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0770

- name: copy kubernetes config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user}}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0770
    remote_src: yes